In [2]:
import pandas as pd
import numpy as np

In [3]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
dic = {'a':10,'b':20,'c':30}

In [4]:
pd.Series(my_list,index = labels)

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(arr,index = labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(dic)

a    10
b    20
c    30
dtype: int64

## Multiple series together is called Dataframe

In [7]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Aman", "Priya", "Rahul", "Sneha", "Karan"],
    "Age": [19, 20, 18, 19, 20],
    "Gender": ["Male", "Female", "Male", "Female", "Male"],
    "Marks": [85, 92, 78, 88, 95],
    "City": ["Jaipur", "Delhi", "Mumbai", "Pune", "Bengaluru"]
}

df = pd.DataFrame(data,index = (1,2,3,4,5))
print(df)

   Student_ID   Name  Age  Gender  Marks       City
1         101   Aman   19    Male     85     Jaipur
2         102  Priya   20  Female     92      Delhi
3         103  Rahul   18    Male     78     Mumbai
4         104  Sneha   19  Female     88       Pune
5         105  Karan   20    Male     95  Bengaluru

In [8]:
students = [
    [101, "Aman", 19, "Male", 85, "Jaipur"],
    [102, "Priya", 20, "Female", 92, "Delhi"],
    [103, "Rahul", 18, "Male", 78, "Mumbai"],
    [104, "Sneha", 19, "Female", 88, "Pune"],
    [105, "Karan", 20, "Male", 95, "Bengaluru"]
]
coloums = ['students_id','Name',"Age",'Gender','Marks','City']
df2 = pd.DataFrame(students, columns=coloums)
df2

   students_id   Name  Age  Gender  Marks       City
0          101   Aman   19    Male     85     Jaipur
1          102  Priya   20  Female     92      Delhi
2          103  Rahul   18    Male     78     Mumbai
3          104  Sneha   19  Female     88       Pune
4          105  Karan   20    Male     95  Bengaluru

## Acessing and Creating and deleting coloums

In [9]:
df[['Name','City']]
df["Designation"] = ["Doctor","Engineer","Scientist","Shopkeeper","Jobless"]


df.drop(["Name","City","Marks"],axis = 1,inplace = True)
df

   Student_ID  Age  Gender Designation
1         101   19    Male      Doctor
2         102   20  Female    Engineer
3         103   18    Male   Scientist
4         104   19  Female  Shopkeeper
5         105   20    Male     Jobless

In [10]:
df.drop(1,axis = 0)

   Student_ID  Age  Gender Designation
2         102   20  Female    Engineer
3         103   18    Male   Scientist
4         104   19  Female  Shopkeeper
5         105   20    Male     Jobless

## Accesing the row

In [11]:
df.loc[[1,2,3]]

   Student_ID  Age  Gender Designation
1         101   19    Male      Doctor
2         102   20  Female    Engineer
3         103   18    Male   Scientist

## Selecting subset of Rows and Coloumn

In [12]:
df.loc[[1,2]][["Gender","Age"]]

   Gender  Age
1    Male   19
2  Female   20

In [13]:
df

   Student_ID  Age  Gender Designation
1         101   19    Male      Doctor
2         102   20  Female    Engineer
3         103   18    Male   Scientist
4         104   19  Female  Shopkeeper
5         105   20    Male     Jobless

## Conditional Statement

In [14]:
df[df["Age"] > 18]
df[(df["Age"] > 18) & (df["Gender"]=="Male")]

   Student_ID  Age Gender Designation
1         101   19   Male      Doctor
5         105   20   Male     Jobless

In [15]:
df2.drop("Name",axis=1)

   students_id  Age  Gender  Marks       City
0          101   19    Male     85     Jaipur
1          102   20  Female     92      Delhi
2          103   18    Male     78     Mumbai
3          104   19  Female     88       Pune
4          105   20    Male     95  Bengaluru

##  Finding Missing data

In [16]:
Missing_data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107],
    "Name": ["Aman", "Priya", "Rahul", "Sneha", "Karan", "Riya", "Arjun"],
    "Age": [19, 20, np.nan, 19, 21, np.nan, 20],
    "Gender": ["Male", "Female", "Male", np.nan, "Male", "Female", "Male"],
    "Marks": [85, np.nan, 78, 88, 95, 90, np.nan],
    "City": ["Jaipur", "Delhi", np.nan, "Pune", "Bengaluru", "Mumbai", "Delhi"]
}
index = [1,2,3,4,5,6,7]
df = pd.DataFrame(Missing_data,index=index)
df.drop(["Student_ID"],axis =1,inplace = True)
df.isna()
df.isna().sum() #count how many null value in each coloumn
df.isna().any() #check is there any coloumn with no null value
df

    Name   Age  Gender  Marks       City
1   Aman  19.0    Male   85.0     Jaipur
2  Priya  20.0  Female    NaN      Delhi
3  Rahul   NaN    Male   78.0        NaN
4  Sneha  19.0     NaN   88.0       Pune
5  Karan  21.0    Male   95.0  Bengaluru
6   Riya   NaN  Female   90.0     Mumbai
7  Arjun  20.0    Male    NaN      Delhi

## Removing Missing Data

In [17]:
df.dropna(thresh=3) #Row wise
df

    Name   Age  Gender  Marks       City
1   Aman  19.0    Male   85.0     Jaipur
2  Priya  20.0  Female    NaN      Delhi
3  Rahul   NaN    Male   78.0        NaN
4  Sneha  19.0     NaN   88.0       Pune
5  Karan  21.0    Male   95.0  Bengaluru
6   Riya   NaN  Female   90.0     Mumbai
7  Arjun  20.0    Male    NaN      Delhi

## Filling the Missing Dataset

In [18]:

values = {
    "Age" : 10 , "Gender" :"Female" , "Marks" : 99 , "City" : "Kolkata"
}
df.fillna(values,inplace = True) #coloumn wise
df

    Name   Age  Gender  Marks       City
1   Aman  19.0    Male   85.0     Jaipur
2  Priya  20.0  Female   99.0      Delhi
3  Rahul  10.0    Male   78.0    Kolkata
4  Sneha  19.0  Female   88.0       Pune
5  Karan  21.0    Male   95.0  Bengaluru
6   Riya  10.0  Female   90.0     Mumbai
7  Arjun  20.0    Male   99.0      Delhi

In [19]:
df

    Name   Age  Gender  Marks       City
1   Aman  19.0    Male   85.0     Jaipur
2  Priya  20.0  Female   99.0      Delhi
3  Rahul  10.0    Male   78.0    Kolkata
4  Sneha  19.0  Female   88.0       Pune
5  Karan  21.0    Male   95.0  Bengaluru
6   Riya  10.0  Female   90.0     Mumbai
7  Arjun  20.0    Male   99.0      Delhi

## Merging ,Joining and Concatenation

In [20]:
# DataFrame 1: Student Details
df1 = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104],
    "Name": ["Aman", "Priya", "Rahul", "Sneha"],
    "Age": [19, 20, 18, 21]
})

# DataFrame 2: Salary and Bonus Details
df2 = pd.DataFrame({
    "Student_ID": [102, 103, 105],
    "Salary": [50000, 60000, 55000],
    "Bonus": [5000, 7000, 6000]
})

pd.merge(df1,df2,on="Student_ID")

   Student_ID   Name  Age  Salary  Bonus
0         102  Priya   20   50000   5000
1         103  Rahul   18   60000   7000

In [21]:
pd.merge(df1,df2,on = "Student_ID",how = 'inner')

   Student_ID   Name  Age  Salary  Bonus
0         102  Priya   20   50000   5000
1         103  Rahul   18   60000   7000

In [22]:
pd.merge(df1,df2,on="Student_ID",how= "outer")

   Student_ID   Name   Age   Salary   Bonus
0         101   Aman  19.0      NaN     NaN
1         102  Priya  20.0  50000.0  5000.0
2         103  Rahul  18.0  60000.0  7000.0
3         104  Sneha  21.0      NaN     NaN
4         105    NaN   NaN  55000.0  6000.0

In [23]:
pd.merge(df1,df2,on="Student_ID",how= "left")

   Student_ID   Name  Age   Salary   Bonus
0         101   Aman   19      NaN     NaN
1         102  Priya   20  50000.0  5000.0
2         103  Rahul   18  60000.0  7000.0
3         104  Sneha   21      NaN     NaN

In [24]:
pd.merge(df1,df2,on='Student_ID',how="right")

   Student_ID   Name   Age  Salary  Bonus
0         102  Priya  20.0   50000   5000
1         103  Rahul  18.0   60000   7000
2         105    NaN   NaN   55000   6000

## Concatenation of 2 Dataframe

In [25]:
df1 = pd.DataFrame({
    "A": ["a1", "a2", "a3"],
    "B": ["b1", "b2", "b3"],
    "C": ["c1", "c2", "c3"]
})

df2 = pd.DataFrame({
    "A": ["a4", "a5", "a6"],
    "B": ["b4", "b5", "b6"],
    "C": ["c4", "c5", "c6"]
})

In [26]:
pd.concat([df1,df2])

    A   B   C
0  a1  b1  c1
1  a2  b2  c2
2  a3  b3  c3
0  a4  b4  c4
1  a5  b5  c5
2  a6  b6  c6

In [27]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  a1  b1  c1  a4  b4  c4
1  a2  b2  c2  a5  b5  c5
2  a3  b3  c3  a6  b6  c6

## Joining 2 dataFrames

In [28]:
df1 = pd.DataFrame({
    "Name" :["Manan","Rahul","Shayam"]
},index = [1,2,3])

df2 = pd.DataFrame({
    "Score" : [45,55,34]
},index = [2,3,4])

In [29]:
df1.join(df2)

     Name  Score
1   Manan    NaN
2   Rahul   45.0
3  Shayam   55.0

In [30]:
df2.join(df1)

   Score    Name
2     45   Rahul
3     55  Shayam
4     34     NaN

In [31]:
df1.join(df2,how = "inner")

     Name  Score
2   Rahul     45
3  Shayam     55

In [32]:
df1.join(df2,how= 'outer')

     Name  Score
1   Manan    NaN
2   Rahul   45.0
3  Shayam   55.0
4     NaN   34.0

## Group-By

In [33]:
df = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Aman", "Priya", "Rahul", "Sneha", "Karan",
             "Riya", "Arjun", "Pooja", "Rohan", "Neha"],
    "Department": ["IT", "HR", "IT", "Finance", "HR",
                   "IT", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 45000, 60000, 55000, 48000,
               62000, 58000, 47000, 65000, 60000],
    "Experience": [2, 1, 3, 4, 2, 5, 3, 1, 6, 4]
})
df.groupby("Department")["Salary"].mean()

Department
Finance    57666.666667
HR         46666.666667
IT         59250.000000
Name: Salary, dtype: float64

In [34]:
df.groupby("Department")["Salary"].sum()

Department
Finance    173000
HR         140000
IT         237000
Name: Salary, dtype: int64

## Multiple Group by

In [35]:
df.groupby(["Experience","Department"])["Salary"].sum()

Experience  Department
1           HR             92000
2           HR             48000
            IT             50000
3           Finance        58000
            IT             60000
4           Finance       115000
5           IT             62000
6           IT             65000
Name: Salary, dtype: int64

In [36]:
for name ,group in df.groupby("Department"):
    print("Department :",name)
    print(group)
    print()

Department : Finance
   Emp_ID   Name Department  Salary  Experience
3     104  Sneha    Finance   55000           4
6     107  Arjun    Finance   58000           3
9     110   Neha    Finance   60000           4

Department : HR
   Emp_ID   Name Department  Salary  Experience
1     102  Priya         HR   45000           1
4     105  Karan         HR   48000           2
7     108  Pooja         HR   47000           1

Department : IT
   Emp_ID   Name Department  Salary  Experience
0     101   Aman         IT   50000           2
2     103  Rahul         IT   60000           3
5     106   Riya         IT   62000           5
8     109  Rohan         IT   65000           6

## Agregation

In [37]:
df["Salary"].agg(["sum", "mean", "min", "max", "std", "median"])

sum       550000.000000
mean       55000.000000
min        45000.000000
max        65000.000000
std         7039.570694
median     56500.000000
Name: Salary, dtype: float64

## Pivot Table

In [38]:
df = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Aman", "Priya", "Rahul", "Sneha", "Karan",
             "Riya", "Arjun", "Pooja", "Rohan", "Neha"],
    "Department": ["IT", "HR", "IT", "Finance", "HR",
                   "IT", "Finance", "HR", "IT", "Finance"],
    "Gender": ["M", "F", "M", "F", "M",
               "F", "M", "F", "M", "F"],
    "Salary": [50000, 45000, 60000, 55000, 48000,
               62000, 58000, 47000, 65000, 60000],
    "Experience": [2, 1, 3, 4, 2, 5, 3, 1, 6, 4]
})


pd.pivot_table(df,
               values = ["Salary","Experience"],
               index = "Name",
               columns = "Department" )

#performing agg function
pd.pivot_table(df,
               values = ["Salary","Experience"],
               index = "Name",
               columns = "Department",aggfunc = "median" )

           Experience             Salary
Department    Finance   HR   IT  Finance       HR       IT
Name
Aman              NaN  NaN  2.0      NaN      NaN  50000.0
Arjun             3.0  NaN  NaN  58000.0      NaN      NaN
Karan             NaN  2.0  NaN      NaN  48000.0      NaN
Neha              4.0  NaN  NaN  60000.0      NaN      NaN
Pooja             NaN  1.0  NaN      NaN  47000.0      NaN
Priya             NaN  1.0  NaN      NaN  45000.0      NaN
Rahul             NaN  NaN  3.0      NaN      NaN  60000.0
Riya              NaN  NaN  5.0      NaN      NaN  62000.0
Rohan             NaN  NaN  6.0      NaN      NaN  65000.0
Sneha             4.0  NaN  NaN  55000.0      NaN      NaN

## Cross tabs

In [39]:
pd.crosstab(df["Name"],df["Department"])

Department  Finance  HR  IT
Name
Aman              0   0   1
Arjun             1   0   0
Karan             0   1   0
Neha              1   0   0
Pooja             0   1   0
Priya             0   1   0
Rahul             0   0   1
Riya              0   0   1
Rohan             0   0   1
Sneha             1   0   0

## Operations

In [40]:
df = pd.DataFrame({
    "Name": ["Aman", "Priya", "Rahul", "Sneha", "Karan", "Riya"],
    "Department": ["IT", "HR", "IT", "HR", "IT", "HR"],
    "Gender": ["M", "F", "M", "F", "M", "F"],
    "Salary": [50000, 45000, 60000, 55000, 70000, 50000]
})

In [41]:
df.shape

(6, 4)

In [42]:
df.columns

Index(['Name', 'Department', 'Gender', 'Salary'], dtype='object')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Department  6 non-null      object
 2   Gender      6 non-null      object
 3   Salary      6 non-null      int64
dtypes: int64(1), object(3)
memory usage: 324.0+ bytes

In [44]:
df.describe()

            Salary
count      6.00000
mean   55000.00000
std     8944.27191
min    45000.00000
25%    50000.00000
50%    52500.00000
75%    58750.00000
max    70000.00000

In [45]:
df["Salary"] + 100000

0    150000
1    145000
2    160000
3    155000
4    170000
5    150000
Name: Salary, dtype: int64

In [46]:
def square(x):
    return x**2

In [47]:
df["Salary"] = df["Salary"].apply(square)

In [48]:
df["New_Salary"] = df["Salary"].apply(square)

In [49]:
df

    Name Department Gender      Salary            New_Salary
0   Aman         IT      M  2500000000   6250000000000000000
1  Priya         HR      F  2025000000   4100625000000000000
2  Rahul         IT      M  3600000000  12960000000000000000
3  Sneha         HR      F  3025000000   9150625000000000000
4  Karan         IT      M  4900000000  24010000000000000000
5   Riya         HR      F  2500000000   6250000000000000000

In [ ]:
amount = 1500
if amount>2000 :
    discount = 20
    print("Discount will be",discount)
elif amount>1000:
    discount =10
    print("Discount will be :",discount)
elif amount>500:
    discount = 5
    print("discount will be",discount)
else:
    print("NO discount")    
discount_amount = amount *(discount /100)  
print("Discount is",discount,"and amount is",discount_amount)

Discount will be : 10
Discount is 10 and amount is 150.0