In [30]:
import pandas as pd
import numpy as np

In [31]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
dic = {'a':10,'b':20,'c':30}

In [32]:
pd.Series(my_list,index = labels)

a    10
b    20
c    30
dtype: int64

In [33]:
pd.Series(arr,index = labels)

a    10
b    20
c    30
dtype: int64

In [34]:
pd.Series(dic)

a    10
b    20
c    30
dtype: int64

## Multiple series together is called Dataframe

In [35]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Aman", "Priya", "Rahul", "Sneha", "Karan"],
    "Age": [19, 20, 18, 19, 20],
    "Gender": ["Male", "Female", "Male", "Female", "Male"],
    "Marks": [85, 92, 78, 88, 95],
    "City": ["Jaipur", "Delhi", "Mumbai", "Pune", "Bengaluru"]
}

df = pd.DataFrame(data,index = (1,2,3,4,5))
print(df)

   Student_ID   Name  Age  Gender  Marks       City
1         101   Aman   19    Male     85     Jaipur
2         102  Priya   20  Female     92      Delhi
3         103  Rahul   18    Male     78     Mumbai
4         104  Sneha   19  Female     88       Pune
5         105  Karan   20    Male     95  Bengaluru

In [36]:
students = [
    [101, "Aman", 19, "Male", 85, "Jaipur"],
    [102, "Priya", 20, "Female", 92, "Delhi"],
    [103, "Rahul", 18, "Male", 78, "Mumbai"],
    [104, "Sneha", 19, "Female", 88, "Pune"],
    [105, "Karan", 20, "Male", 95, "Bengaluru"]
]
coloums = ['students_id','Name',"Age",'Gender','Marks','City']
df2 = pd.DataFrame(students, columns=coloums)
df2

   students_id   Name  Age  Gender  Marks       City
0          101   Aman   19    Male     85     Jaipur
1          102  Priya   20  Female     92      Delhi
2          103  Rahul   18    Male     78     Mumbai
3          104  Sneha   19  Female     88       Pune
4          105  Karan   20    Male     95  Bengaluru

## Acessing and Creating and deleting coloums

In [37]:
df[['Name','City']]
df["Designation"] = ["Doctor","Engineer","Scientist","Shopkeeper","Jobless"]


df.drop(["Name","City","Marks"],axis = 1,inplace = True)
df

   Student_ID  Age  Gender Designation
1         101   19    Male      Doctor
2         102   20  Female    Engineer
3         103   18    Male   Scientist
4         104   19  Female  Shopkeeper
5         105   20    Male     Jobless

In [38]:
df.drop(1,axis = 0)

   Student_ID  Age  Gender Designation
2         102   20  Female    Engineer
3         103   18    Male   Scientist
4         104   19  Female  Shopkeeper
5         105   20    Male     Jobless

## Accesing the row

In [39]:
df.loc[[1,2,3]]

   Student_ID  Age  Gender Designation
1         101   19    Male      Doctor
2         102   20  Female    Engineer
3         103   18    Male   Scientist

## Selecting subset of Rows and Coloumn

In [40]:
df.loc[[1,2]][["Gender","Age"]]

   Gender  Age
1    Male   19
2  Female   20

In [41]:
df

   Student_ID  Age  Gender Designation
1         101   19    Male      Doctor
2         102   20  Female    Engineer
3         103   18    Male   Scientist
4         104   19  Female  Shopkeeper
5         105   20    Male     Jobless

## Conditional Statement

In [42]:
df[df["Age"] > 18]
df[(df["Age"] > 18) & (df["Gender"]=="Male")]

   Student_ID  Age Gender Designation
1         101   19   Male      Doctor
5         105   20   Male     Jobless

In [43]:
df2.drop("Name",axis=1)

   students_id  Age  Gender  Marks       City
0          101   19    Male     85     Jaipur
1          102   20  Female     92      Delhi
2          103   18    Male     78     Mumbai
3          104   19  Female     88       Pune
4          105   20    Male     95  Bengaluru

##  Finding Missing data

In [44]:
Missing_data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107],
    "Name": ["Aman", "Priya", "Rahul", "Sneha", "Karan", "Riya", "Arjun"],
    "Age": [19, 20, np.nan, 19, 21, np.nan, 20],
    "Gender": ["Male", "Female", "Male", np.nan, "Male", "Female", "Male"],
    "Marks": [85, np.nan, 78, 88, 95, 90, np.nan],
    "City": ["Jaipur", "Delhi", np.nan, "Pune", "Bengaluru", "Mumbai", "Delhi"]
}
index = [1,2,3,4,5,6,7]
df = pd.DataFrame(Missing_data,index=index)
df.drop(["Student_ID"],axis =1,inplace = True)
df.isna()
df.isna().sum() #count how many null value in each coloumn
df.isna().any() #check is there any coloumn with no null value
df

    Name   Age  Gender  Marks       City
1   Aman  19.0    Male   85.0     Jaipur
2  Priya  20.0  Female    NaN      Delhi
3  Rahul   NaN    Male   78.0        NaN
4  Sneha  19.0     NaN   88.0       Pune
5  Karan  21.0    Male   95.0  Bengaluru
6   Riya   NaN  Female   90.0     Mumbai
7  Arjun  20.0    Male    NaN      Delhi

## Removing Missing Data

In [45]:
df.dropna(thresh=3) #Row wise
df

    Name   Age  Gender  Marks       City
1   Aman  19.0    Male   85.0     Jaipur
2  Priya  20.0  Female    NaN      Delhi
3  Rahul   NaN    Male   78.0        NaN
4  Sneha  19.0     NaN   88.0       Pune
5  Karan  21.0    Male   95.0  Bengaluru
6   Riya   NaN  Female   90.0     Mumbai
7  Arjun  20.0    Male    NaN      Delhi

## Filling the Missing Dataset

In [46]:

values = {
    "Age" : 10 , "Gender" :"Female" , "Marks" : 99 , "City" : "Kolkata"
}
df.fillna(values,inplace = True) #coloumn wise
df

    Name   Age  Gender  Marks       City
1   Aman  19.0    Male   85.0     Jaipur
2  Priya  20.0  Female   99.0      Delhi
3  Rahul  10.0    Male   78.0    Kolkata
4  Sneha  19.0  Female   88.0       Pune
5  Karan  21.0    Male   95.0  Bengaluru
6   Riya  10.0  Female   90.0     Mumbai
7  Arjun  20.0    Male   99.0      Delhi

In [47]:
df

    Name   Age  Gender  Marks       City
1   Aman  19.0    Male   85.0     Jaipur
2  Priya  20.0  Female   99.0      Delhi
3  Rahul  10.0    Male   78.0    Kolkata
4  Sneha  19.0  Female   88.0       Pune
5  Karan  21.0    Male   95.0  Bengaluru
6   Riya  10.0  Female   90.0     Mumbai
7  Arjun  20.0    Male   99.0      Delhi

## Merging ,Joining and Concatenation

In [48]:
# DataFrame 1: Student Details
df1 = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104],
    "Name": ["Aman", "Priya", "Rahul", "Sneha"],
    "Age": [19, 20, 18, 21]
})

# DataFrame 2: Salary and Bonus Details
df2 = pd.DataFrame({
    "Student_ID": [102, 103, 105],
    "Salary": [50000, 60000, 55000],
    "Bonus": [5000, 7000, 6000]
})

pd.merge(df1,df2,on="Student_ID")

   Student_ID   Name  Age  Salary  Bonus
0         102  Priya   20   50000   5000
1         103  Rahul   18   60000   7000

In [49]:
pd.merge(df1,df2,on = "Student_ID",how = 'inner')

   Student_ID   Name  Age  Salary  Bonus
0         102  Priya   20   50000   5000
1         103  Rahul   18   60000   7000

In [50]:
pd.merge(df1,df2,on="Student_ID",how= "outer")

   Student_ID   Name   Age   Salary   Bonus
0         101   Aman  19.0      NaN     NaN
1         102  Priya  20.0  50000.0  5000.0
2         103  Rahul  18.0  60000.0  7000.0
3         104  Sneha  21.0      NaN     NaN
4         105    NaN   NaN  55000.0  6000.0

In [51]:
pd.merge(df1,df2,on="Student_ID",how= "left")

   Student_ID   Name  Age   Salary   Bonus
0         101   Aman   19      NaN     NaN
1         102  Priya   20  50000.0  5000.0
2         103  Rahul   18  60000.0  7000.0
3         104  Sneha   21      NaN     NaN

In [52]:
pd.merge(df1,df2,on='Student_ID',how="right")

   Student_ID   Name   Age  Salary  Bonus
0         102  Priya  20.0   50000   5000
1         103  Rahul  18.0   60000   7000
2         105    NaN   NaN   55000   6000

## Concatenation of 2 Dataframe

In [56]:
df1 = pd.DataFrame({
    "A": ["a1", "a2", "a3"],
    "B": ["b1", "b2", "b3"],
    "C": ["c1", "c2", "c3"]
})

df2 = pd.DataFrame({
    "A": ["a4", "a5", "a6"],
    "B": ["b4", "b5", "b6"],
    "C": ["c4", "c5", "c6"]
})

In [62]:
pd.concat([df1,df2])

    A   B   C
0  a1  b1  c1
1  a2  b2  c2
2  a3  b3  c3
0  a4  b4  c4
1  a5  b5  c5
2  a6  b6  c6

In [63]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  a1  b1  c1  a4  b4  c4
1  a2  b2  c2  a5  b5  c5
2  a3  b3  c3  a6  b6  c6

## Joining 2 dataFrames

In [68]:
df1 = pd.DataFrame({
    "Name" :["Manan","Rahul","Shayam"]
},index = [1,2,3])

df2 = pd.DataFrame({
    "Score" : [45,55,34]
},index = [2,3,4])

In [69]:
df1.join(df2)

     Name  Score
1   Manan    NaN
2   Rahul   45.0
3  Shayam   55.0

In [70]:
df2.join(df1)

   Score    Name
2     45   Rahul
3     55  Shayam
4     34     NaN

In [71]:
df1.join(df2,how = "inner")

     Name  Score
2   Rahul     45
3  Shayam     55

In [72]:
df1.join(df2,how= 'outer')

     Name  Score
1   Manan    NaN
2   Rahul   45.0
3  Shayam   55.0
4     NaN   34.0